/**
 * Active-check stop/cancel path regression tests.
 *
 * Verifies the four stop/cancel paths for the active-check workflow:
 *   1. Cancel queued item  — /api/cancel-queued
 *   2. Cancel running item — /api/cancel-running
 *   3. Force stop task     — /api/task/force-stop
 *   4. Stop all daemons   — uses workflowNameFromInstance("Active Check N")
 *
 * active-check uses batch.mode="shared-context-pool" (poolSize: 4). These
 * tests verify the SQLite-backed cancel/stop handlers correctly handle
 * active-check tasks — the workflow name is the only thing distinguishing
 * active-check from separations in the control-DB layer.
 *
 * Tests A–D from the Phase-A / Task-4b audit plan:
 *   A: workflowNameFromInstance returns "active-check" for active-check instances
 *   B: daemon-stop filtering correctly distinguishes active-check instances
 *   C: cancel_task command is written for an active-check task
 *   D: cancellation of queued active-check task writes BOTH tracker row AND JSONL log line
 */
import { describe, it, beforeEach, afterEach } from "vitest";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { readLogEntries } from "../../../src/tracker/jsonl.js";
import { emitTrackerRow } from "../../../src/tracker/jsonl-io.js";
import { openControlDb } from "../../../src/core/control-db.js";
import { createTaskStore } from "../../../src/core/task-store/index.js";
import { createWorkerStore } from "../../../src/core/daemon/worker-store.js";
import {
  buildCancelQueuedHandler,
  buildCancelRunningHandler,
} from "../../../src/control/ops/index.js";
import { queueFilePath } from "../../../src/core/daemon/queue.js";
import {
  workflowNameFromInstance,
  INSTANCE_LABELS,
} from "../../../src/tracker/session-events.js";
import type { QueueEvent } from "../../../src/core/daemon/types.js";

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "ac-cancel-"));
});
afterEach(() => {
  if (tmp && existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
});

// ── Test A: workflowNameFromInstance for active-check ──────────────────────
//
// This is confirmed by the existing test in session-events.test.ts:
//   workflowNameFromInstance("Active Check 1") === "active-check"
//   workflowNameFromInstance("active-check 1") === "active-check"
// We add one more assertion here to confirm the label is registered and
// the INSTANCE_LABELS mapping is bidirectional.

describe("Test A: workflowNameFromInstance — active-check label resolution", () => {
  it("resolves 'Active Check N' to 'active-check'", () => {
    // Standard label format generated by generateInstanceName("active-check")
    assert.equal(workflowNameFromInstance("Active Check 1"), "active-check");
    assert.equal(workflowNameFromInstance("Active Check 2"), "active-check");
    assert.equal(workflowNameFromInstance("Active Check 10"), "active-check");
  });

  it("INSTANCE_LABELS has 'active-check' → 'Active Check' mapping", () => {
    assert.equal(INSTANCE_LABELS["active-check"], "Active Check");
  });

  it("does NOT resolve an unrelated workflow instance as active-check", () => {
    // Regression guard: ensure substring matching doesn't cause false positives.
    // "Active Check" should NOT match "EID Lookup 1" or "Separation 1"
    assert.notEqual(workflowNameFromInstance("EID Lookup 1"), "active-check");
    assert.notEqual(workflowNameFromInstance("Separation 1"), "active-check");
    assert.notEqual(workflowNameFromInstance("Onboarding 1"), "active-check");
  });

  it("returns null for an unrecognized instance name", () => {
    assert.equal(workflowNameFromInstance("Unknown Workflow 1"), null);
    assert.equal(workflowNameFromInstance("Active 1"), null); // partial label — must not match
    assert.equal(workflowNameFromInstance("Check 1"), null);
  });
});

// ── Test B: daemon-stop per-instance kill loop targeting ──────────────────
//
// The /api/daemon/stop route's kill loop uses:
//   workflowNameFromInstance(event.workflowInstance) !== workflow
// to filter session events by target workflow. We verify:
//   - Active Check events are selected when workflow="active-check"
//   - Separation events are NOT selected when workflow="active-check"
//
// This tests the pure filtering logic without spinning up the HTTP route.

describe("Test B: daemon-stop filtering selects active-check instances only", () => {
  it("workflowNameFromInstance filters correctly for active-check vs other workflows", () => {
    const instances = [
      { workflowInstance: "Active Check 1", expected: true },
      { workflowInstance: "Active Check 2", expected: true },
      { workflowInstance: "Separation 1", expected: false },
      { workflowInstance: "EID Lookup 1", expected: false },
      { workflowInstance: "Onboarding 1", expected: false },
      { workflowInstance: "Work Study 1", expected: false },
      { workflowInstance: "Oath Upload 1", expected: false },
    ];

    const workflow = "active-check";
    for (const { workflowInstance, expected } of instances) {
      const resolved = workflowNameFromInstance(workflowInstance);
      const selected = resolved === workflow;
      assert.equal(
        selected,
        expected,
        `Expected workflowInstance="${workflowInstance}" to be ${expected ? "selected" : "excluded"} ` +
          `for workflow="${workflow}" but workflowNameFromInstance returned "${resolved}"`,
      );
    }
  });

  it("active-check instances are not selected for other workflow stop commands", () => {
    const activeCheckInstances = ["Active Check 1", "Active Check 2"];
    const otherWorkflows = ["separations", "eid-lookup", "onboarding", "work-study", "oath-upload"];

    for (const instance of activeCheckInstances) {
      const resolved = workflowNameFromInstance(instance);
      for (const otherWorkflow of otherWorkflows) {
        assert.notEqual(
          resolved,
          otherWorkflow,
          `Active Check instance "${instance}" should not be targeted by ${otherWorkflow} stop`,
        );
      }
    }
  });
});

// ── Test C: cancel_task worker command written for active-check task ───────
//
// Verifies that buildCancelQueuedHandler creates a cancel_task worker command
// in the SQLite worker_commands table for an active-check task, and transitions
// the task to "cancelled".

describe("Test C: buildCancelQueuedHandler writes cancel_task command for active-check", () => {
  it("cancels a queued active-check SQLite task and writes a completed cancel_task command", async () => {
    const control = openControlDb({ trackerDir: tmp });
    const taskStore = createTaskStore(control);
    const workerStore = createWorkerStore(control);
    const [enqueued] = taskStore.enqueueTasks({
      workflow: "active-check",
      inputs: [{ name: "Doe, John" }],
      deriveItemId: (input) => input.name,
      runIds: ["ac-run-queued"],
    });

    emitTrackerRow(
      {
        workflow: "active-check",
        timestamp: new Date().toISOString(),
        id: "Doe, John",
        runId: "ac-run-queued",
        status: "pending",
        data: { archetype: "single", name: "Doe, John" },
      },
      tmp,
    );

    const result = await buildCancelQueuedHandler(tmp)({
      workflow: "active-check",
      id: "Doe, John",
      runId: "ac-run-queued",
    });

    assert.equal(result.ok, true, `Expected ok=true but got: ${JSON.stringify(result)}`);
    // Task must be in cancelled state
    assert.equal(taskStore.getTask(enqueued.taskId)?.state, "cancelled");
    assert.equal(taskStore.getAttempt(enqueued.attemptId)?.state, "cancelled");
    // A cancel_task command must have been written (in "completed" state for queued items)
    const commands = workerStore.db
      .prepare("SELECT * FROM worker_commands WHERE workflow = 'active-check'")
      .all() as Array<{ command_type: string; state: string; target_task_id: string }>;
    assert.equal(commands.length, 1, "Expected exactly one worker command for active-check cancel");
    assert.equal(commands[0].command_type, "cancel_task");
    assert.equal(commands[0].state, "completed");
    assert.equal(commands[0].target_task_id, enqueued.taskId);
    workerStore.close();
    taskStore.close();
  });

  it("returns 409 when active-check task is already running (claimed)", async () => {
    const control = openControlDb({ trackerDir: tmp });
    const taskStore = createTaskStore(control);
    const [enqueued] = taskStore.enqueueTasks({
      workflow: "active-check",
      inputs: [{ name: "Garcia, Maria" }],
      deriveItemId: (input) => input.name,
      runIds: ["ac-run-running"],
    });
    taskStore.claimNextTask({ workflow: "active-check", workerId: "ac-worker-1" });
    taskStore.markTaskRunning({
      taskId: enqueued.taskId,
      attemptId: enqueued.attemptId,
      workerId: "ac-worker-1",
    });

    const result = await buildCancelQueuedHandler(tmp)({
      workflow: "active-check",
      id: "Garcia, Maria",
      runId: "ac-run-running",
    });

    assert.equal(result.ok, false);
    assert.equal((result as { status?: number }).status, 409);
    taskStore.close();
  });
});

// ── Test D: cancel queued active-check writes BOTH tracker row AND log line ─
//
// The previous-continuation fix in emitDashboardCancelTrackerRow (shared.ts)
// calls BOTH trackEvent (tracker failed/cancelled row) AND appendLogEntry
// (JSONL log line). This test verifies both outputs for active-check.

describe("Test D: cancel queued active-check writes tracker row + JSONL log line", () => {
  it("writes a tracker failed/step:cancelled row AND a JSONL log line on queue cancel (SQLite path)", async () => {
    const control = openControlDb({ trackerDir: tmp });
    const taskStore = createTaskStore(control);
    const workerStore = createWorkerStore(control);
    taskStore.enqueueTasks({
      workflow: "active-check",
      inputs: [{ name: "Smith, Jane" }],
      deriveItemId: (input) => input.name,
      runIds: ["ac-run-D"],
    });

    emitTrackerRow(
      {
        workflow: "active-check",
        timestamp: new Date().toISOString(),
        id: "Smith, Jane",
        runId: "ac-run-D",
        status: "pending",
        data: { archetype: "single", name: "Smith, Jane" },
      },
      tmp,
    );

    const result = await buildCancelQueuedHandler(tmp)({
      workflow: "active-check",
      id: "Smith, Jane",
      runId: "ac-run-D",
    });

    assert.equal(result.ok, true);

    // Verify tracker row: active-check-<date>.jsonl must contain a failed+step=cancelled row
    const trackerFile = readdirSync(tmp).find((file) =>
      /^active-check-\d{4}-\d{2}-\d{2}\.jsonl$/.test(file),
    );
    assert.ok(
      trackerFile,
      `Expected an active-check tracker file but found: [${readdirSync(tmp).join(", ")}]`,
    );
    const trackerContent = readFileSync(join(tmp, trackerFile), "utf8");
    const trackerEntries = trackerContent
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((l) => JSON.parse(l));
    const cancelledEntry = trackerEntries.find(
      (e: { runId?: string; status?: string; step?: string }) =>
        e.runId === "ac-run-D" && e.status === "failed",
    );
    assert.ok(cancelledEntry, "Expected a failed tracker entry for active-check runId=ac-run-D");
    assert.equal(
      cancelledEntry.step,
      "cancelled",
      `Expected step="cancelled" but got step="${cancelledEntry.step}"`,
    );
    assert.match(
      cancelledEntry.error,
      /cancelled by user from dashboard/,
      "Expected error to mention 'cancelled by user from dashboard'",
    );

    // Verify JSONL log line: active-check-<date>-logs.jsonl must contain a log entry
    const logs = readLogEntries("active-check", "Smith, Jane", tmp);
    assert.ok(logs.length >= 1, `Expected at least one log entry but got ${logs.length}`);
    const cancelLog = logs.find(
      (l) => l.runId === "ac-run-D",
    );
    assert.ok(cancelLog, "Expected a log entry for runId=ac-run-D");
    assert.match(
      cancelLog.message,
      /cancelled by user from dashboard/,
      `Expected log message to mention 'cancelled by user from dashboard' but got: "${cancelLog.message}"`,
    );

    workerStore.close();
    taskStore.close();
  });

  it("returns 404 cancel-queued when queue audit JSONL exists but SQLite has no task row", async () => {
    const path = queueFilePath("active-check", tmp);
    mkdirSync(join(tmp, "daemons"), { recursive: true });
    const enqueueEv: QueueEvent = {
      type: "enqueue",
      id: "Chen, Alice",
      workflow: "active-check",
      input: { name: "Chen, Alice" },
      enqueuedAt: "2026-05-06T10:00:00.000Z",
      enqueuedBy: "test",
      runId: "ac-jsonl-run",
    };
    writeFileSync(path, JSON.stringify(enqueueEv) + "\n");

    const result = await buildCancelQueuedHandler(tmp)({
      workflow: "active-check",
      id: "Chen, Alice",
      runId: "ac-jsonl-run",
    });

    assert.equal(result.ok, false);
    assert.equal(result.status, 404);
    const queueContent = readFileSync(path, "utf8");
    assert.ok(
      !queueContent.includes('"type":"failed"'),
      "SQLite-only cancel must not mutate the append-only audit file",
    );
  });
});

// ── Supplemental: buildCancelRunningHandler for active-check ───────────────
//
// Verify that cancelling a running active-check task via the
// /api/cancel-running path writes a cancel_task command targeting the
// worker that owns the task. This exercises the path that active-check
// daemon workers poll.

describe("buildCancelRunningHandler for active-check tasks", () => {
  it("queues cancel_task for the owning worker when active-check task is running", async () => {
    const control = openControlDb({ trackerDir: tmp });
    const taskStore = createTaskStore(control);
    const workerStore = createWorkerStore(control);
    workerStore.registerWorker({
      workerId: "ac-pool-worker-1",
      workflow: "active-check",
      kind: "daemon",
      pid: 22222,
      hostname: "test-host",
      phase: "processing",
    });
    const [enqueued] = taskStore.enqueueTasks({
      workflow: "active-check",
      inputs: [{ name: "Lee, Kevin" }],
      deriveItemId: (input) => input.name,
      runIds: ["ac-run-cancel-running"],
    });
    taskStore.claimNextTask({ workflow: "active-check", workerId: "ac-pool-worker-1" });
    taskStore.markTaskRunning({
      taskId: enqueued.taskId,
      attemptId: enqueued.attemptId,
      workerId: "ac-pool-worker-1",
    });

    const result = await buildCancelRunningHandler(tmp)({
      workflow: "active-check",
      id: "Lee, Kevin",
      runId: "ac-run-cancel-running",
    });

    assert.equal(result.ok, true);
    assert.equal(result.mode, "worker-command");
    // Task must be in cancel_requested state
    assert.equal(taskStore.getTask(enqueued.taskId)?.state, "cancel_requested");
    // Command must be queued for the owning worker
    const command = workerStore.getCommand(result.commandId);
    assert.equal(command?.commandType, "cancel_task");
    assert.equal(command?.state, "queued");
    assert.equal(command?.targetWorkerId, "ac-pool-worker-1");
    assert.equal(command?.targetTaskId, enqueued.taskId);
    // A cancellation-requested log line should be written
    const logs = readLogEntries("active-check", "Lee, Kevin", tmp);
    assert.ok(logs.length >= 1, `Expected at least one log entry but got ${logs.length}`);
    assert.match(logs[0].message, /Cancellation requested by dashboard/);
    workerStore.close();
    taskStore.close();
  });
});

// Force-stop test removed as part of Contract 5 (2026-05-23): there is no
// separate force-stop path now. `buildCancelRunningHandler` (covered above)
// dispatches a `cancel_task` worker command that — via the kernel's per-run
// AbortController + Page proxy — propagates into in-flight Playwright work
// within ms without killing chrome, which is what the old force-stop tried
// to provide via the about:blank navigation.
