export const TRACKER_COLUMNS = [
  { header: "First Name", key: "firstName", width: 15 },
  { header: "Middle Name", key: "middleName", width: 15 },
  { header: "Last Name", key: "lastName", width: 15 },
  { header: "SSN", key: "ssn", width: 15 },
  { header: "DOB", key: "dob", width: 12 },
  { header: "Phone", key: "phone", width: 15 },
  { header: "Email", key: "email", width: 25 },
  { header: "Address", key: "address", width: 25 },
  { header: "City", key: "city", width: 15 },
  { header: "State", key: "state", width: 8 },
  { header: "Postal Code", key: "postalCode", width: 12 },
  { header: "Dept #", key: "departmentNumber", width: 10 },
  { header: "Recruitment #", key: "recruitmentNumber", width: 15 },
  { header: "Position #", key: "positionNumber", width: 12 },
  { header: "Wage", key: "wage", width: 15 },
  { header: "Effective Date", key: "effectiveDate", width: 14 },
  { header: "Appointment", key: "appointment", width: 12 },
  { header: "CRM Extraction", key: "crmExtraction", width: 14 },
  { header: "Person Search", key: "personSearch", width: 14 },
  { header: "Rehire", key: "rehire", width: 8 },
  { header: "I9 Record", key: "i9Record", width: 12 },
  { header: "Transaction", key: "transaction", width: 14 },
  { header: "PDF Download", key: "pdfDownload", width: 14 },
  { header: "I9 Profile ID", key: "i9ProfileId", width: 14 },
  { header: "Status", key: "status", width: 12 },
  { header: "Error", key: "error", width: 30 },
  { header: "Timestamp", key: "timestamp", width: 22 },
];
