import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync, readdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { z } from 'zod'
import { defineWorkflow, runWorkflow } from '../../../src/core/index.js'
import type { SystemConfig } from '../../../src/core/types.js'

const TMP = () => mkdtempSync(join(tmpdir(), 'hrauto-observer-'))

const fakeLaunch = async ({ system: _system }: { system: SystemConfig }) => ({
  page: {
    bringToFront: async () => {},
    goto: async () => {},
    waitForTimeout: async () => {},
    isClosed: () => false,
    url: () => 'about:blank',
    evaluate: async () => 1,
    screenshot: async () => {},
  } as unknown as import('playwright').Page,
  context: { close: async () => {} } as unknown as import('playwright').BrowserContext,
  browser: null as never,
})

function readSessions(dir: string): any[] {
  const p = join(dir, 'sessions.jsonl')
  try {
    return readFileSync(p, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l))
  } catch {
    return []
  }
}

test('runWorkflow: observer bridges Session.launch hooks to sessionCtx + setStep', async () => {
  const dir = TMP()
  const loginInstances: Array<string | undefined> = []

  const wf = defineWorkflow({
    name: 'test-obs',
    systems: [{
      id: 'ucpath',
      login: async (_page, instance) => { loginInstances.push(instance) },
    }],
    // auth:ucpath is auto-prepended by the registry; 'work' is the only declared step.
    steps: ['work'] as const,
    schema: z.object({}).passthrough(),
    tiling: 'single',
    authChain: 'sequential',
    handler: async (ctx) => { ctx.markStep('work') },
  })

  await runWorkflow(wf, {}, { launchFn: fakeLaunch, trackerDir: dir })

  // 1. sessions.jsonl inside trackerDir contains session_create + browser_launch + auth_start/complete.
  const events = readSessions(dir)
  const types = events.map((e) => e.type)
  assert.ok(types.includes('workflow_start'), `sessions missing workflow_start: ${types.join(',')}`)
  assert.ok(types.includes('session_create'), `sessions missing session_create: ${types.join(',')}`)
  assert.ok(types.includes('browser_launch'), `sessions missing browser_launch: ${types.join(',')}`)
  assert.ok(types.includes('auth_start'), `sessions missing auth_start: ${types.join(',')}`)
  assert.ok(types.includes('auth_complete'), `sessions missing auth_complete: ${types.join(',')}`)

  // 2. instance was threaded to system.login.
  assert.equal(loginInstances.length, 1)
  assert.ok(loginInstances[0], 'login received an instance name')
  // Instance name is generated by `generateInstanceName(workflowName)` — unknown
  // workflows (not in the known-labels map) fall through to the raw workflow
  // name with a numeric suffix, e.g. "test-obs 1".
  assert.match(loginInstances[0]!, /test[-\s]obs/i, `got: ${loginInstances[0]}`)

  // 3. Entry's tracker jsonl has a `running` entry with step 'ucpath-auth' (from onAuthStart → setStep).
  const entryFiles = readdirSync(dir).filter((f) => f.startsWith('test-obs-') && f.endsWith('.jsonl') && !f.endsWith('-logs.jsonl'))
  const lines = readFileSync(join(dir, entryFiles[0]), 'utf8').trim().split('\n').map((l) => JSON.parse(l))
  const runningSteps = lines.filter((l: any) => l.status === 'running').map((l: any) => l.step)
  // auth:ucpath is auto-prepended by the registry and emitted via makeAuthObserver on onAuthStart.
  assert.ok(runningSteps.includes('auth:ucpath'), `running entries missing auth:ucpath: ${runningSteps.join(',')}`)
})

test('runWorkflow: observer guards setStep against undeclared step names', async () => {
  const dir = TMP()

  // "mystery-auth" is not in steps — onAuthStart for systemId "mystery" would try
  // setStep("mystery-auth"), which must be a no-op since it's undeclared.
  const wf = defineWorkflow({
    name: 'test-undecl',
    systems: [{ id: 'mystery', login: async () => {} }],
    steps: ['work'] as const, // no "mystery-auth"
    schema: z.object({}).passthrough(),
    tiling: 'single',
    authChain: 'sequential',
    handler: async (ctx) => { ctx.markStep('work') },
  })

  await runWorkflow(wf, {}, { launchFn: fakeLaunch, trackerDir: dir })

  const entryFiles = readdirSync(dir).filter((f) => f.startsWith('test-undecl-') && f.endsWith('.jsonl') && !f.endsWith('-logs.jsonl'))
  const lines = readFileSync(join(dir, entryFiles[0]), 'utf8').trim().split('\n').map((l) => JSON.parse(l))
  const runningSteps = lines.filter((l: any) => l.status === 'running').map((l: any) => l.step)
  assert.ok(!runningSteps.includes('mystery-auth'), 'must not emit unregistered step name')
  // Session events still emit regardless of step-name matching.
  const events = readSessions(dir).map((e) => e.type)
  assert.ok(events.includes('auth_start'), 'auth_start still fires even without declared step')
})
